apiVersion: v1
kind: Pod
metadata: 
   name: curl-custom-sa-token
   namespace: lab4
   labels:
     week: "week11"
spec:
  serviceAccountName: simran01
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep", "999999"]
